### ISSUE TITLE
scrypt.js's npm page's homepage and repository links are 404'd

### ISSUE THREAD

**Issue by davidmurdoch** [axic/scrypt.js#4]
On https://www.npmjs.com/package/scrypt.js the links still lead to a 404 error.

https://github.com/axic/scrypt.js/commit/b4e8229882565f72dc6cb00ae7a4ccaf4059533e fixes this, but it appears a new version was not published to npm.

**Comment by axic** [comment]
Fixed by #2. Published 0.2.1.
